import type { HeroTemplate, Rarity, Stats } from "./types"

// Default zero stat block helper
const z: Stats = {
  hp: 0,
  atk: 0,
  mag: 0,
  def: 0,
  res: 0,
  spd: 0,
  crit: 0,
  critDmg: 0,
  acc: 0,
  eva: 0,
  lifesteal: 0,
}

const s = (over: Partial<Stats>): Stats => ({ ...z, ...over })

// 48 heroes across 6 rarities (common 5, rare 8, epic 10, legendary 11, mythic 7, celestial 7)
export const HEROES: HeroTemplate[] = [
  // ============================================================
  // COMMON (5)
  // ============================================================
  {
    id: "h_borin",
    name: "Borin Thạch Phủ",
    title: "Lính Đánh Thuê Vùng Biên",
    rarity: "common",
    range: "melee",
    role: "warrior",
    origins: ["human"],
    baseStats: s({ hp: 850, atk: 110, def: 60, res: 40, spd: 90, crit: 5, critDmg: 150, acc: 95 }),
    growth: { hp: 65, atk: 9, def: 5, res: 3, spd: 1 },
    skills: ["slash", "doubleStrike", "whirlwind"],
    bonusSkills: [
      { skillId: "executioner", unlockCondition: { type: "heroLevel", level: 30 } },
      { skillId: "bleedSlash", unlockCondition: { type: "allSkillsLevel", level: 3 } },
    ],
    passive: "ironWill",
    build: "bruiser",
    flavor: "Một cựu lính đánh thuê dày dạn, với chiếc rìu đôi và lời thề bảo vệ kẻ yếu.",
  },
  {
    id: "h_lyrra",
    name: "Lyrra Thanh Phong",
    title: "Cung Thủ Rừng Xanh",
    rarity: "common",
    range: "ranged",
    role: "marksman",
    origins: ["human"],
    baseStats: s({ hp: 720, atk: 105, def: 35, res: 35, spd: 115, crit: 15, critDmg: 160, acc: 100 }),
    growth: { hp: 50, atk: 10, spd: 2, crit: 0.5 },
    skills: ["pierceShot", "rapidFire", "volley"],
        bonusSkills: [
      { skillId: "windArrow", unlockCondition: { type: "heroLevel", level: 20 } },
      { skillId: "phantomArrow", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "marksmanship",
    build: "attack-speed",
    flavor: "Cung thủ trẻ tuổi với mũi tên không bao giờ chệch hướng giữa làn gió rừng.",
  },
  {
    id: "h_grom",
    name: "Grom Răng Sói",
    title: "Chiến Binh Bộ Lạc",
    rarity: "common",
    range: "melee",
    role: "warrior",
    origins: ["beastkin"],
    baseStats: s({ hp: 920, atk: 118, def: 55, res: 30, spd: 100, crit: 8, critDmg: 150, acc: 95 }),
    growth: { hp: 70, atk: 10, def: 4, spd: 1 },
    skills: ["slash", "feralLeap", "whirlwind"],
        bonusSkills: [
      { skillId: "packHowl", unlockCondition: { type: "heroLevel", level: 20 } },
      { skillId: "berserkerRage", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "feralInstinct",
    build: "bruiser",
    flavor: "Hậu duệ bộ lạc sói tuyết, săn dữ thú từ tuổi mười ba.",
  },
  {
    id: "h_mirelle",
    name: "Mirelle Hồ Bích",
    title: "Học Trò Pháp Sư",
    rarity: "common",
    range: "ranged",
    role: "mage",
    origins: ["human"],
    baseStats: s({ hp: 640, atk: 50, mag: 130, def: 30, res: 60, spd: 95, crit: 10, critDmg: 150 }),
    growth: { hp: 45, mag: 12, res: 3 },
    skills: ["arcaneBolt", "fireball", "chainLightning"],
        bonusSkills: [
      { skillId: "manaShatter", unlockCondition: { type: "heroLevel", level: 18 } },
      { skillId: "spellMirror", unlockCondition: { type: "allSkillsLevel", level: 3 } },
    ],
    passive: "arcaneAffinity",
    build: "burst",
    flavor: "Cô gái ham hiểu biết, học tinh thuật từ một quyển sách cũ trong rừng.",
  },
  {
    id: "h_otto",
    name: "Otto Khiên Sắt",
    title: "Cận Vệ Thành Phố",
    rarity: "common",
    range: "melee",
    role: "tank",
    origins: ["human"],
    baseStats: s({ hp: 1200, atk: 80, def: 100, res: 75, spd: 70, crit: 3, critDmg: 150, acc: 95 }),
    growth: { hp: 100, atk: 6, def: 8, res: 4 },
    skills: ["shieldBash", "ironBulwark", "taunt"],
        bonusSkills: [
      { skillId: "immovableStance", unlockCondition: { type: "heroLevel", level: 20 } },
      { skillId: "fortressBreaker", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "fortress",
    build: "tank",
    flavor: "Lính cận vệ trung thành, chiếc khiên đã chặn cả ngàn mũi tên.",
  },

  // ============================================================
  // RARE (5)
  // ============================================================
  {
    id: "h_zara",
    name: "Zara Lưỡi Bóng",
    title: "Sát Thủ Hội Trăng",
    rarity: "rare",
    range: "melee",
    role: "assassin",
    origins: ["human", "outlaw"],
    baseStats: s({ hp: 780, atk: 145, def: 40, res: 40, spd: 130, crit: 25, critDmg: 180, acc: 100 }),
    growth: { hp: 55, atk: 13, spd: 2, crit: 1 },
    skills: ["shadowStrike", "bladeDance", "deathMark"],
    bonusSkills: [
      { skillId: "finalEclipse", unlockCondition: { type: "twoSkillsMaxLevel" } },
      { skillId: "poisonDart", unlockCondition: { type: "heroLevel", level: 25 } },
    ],
    passive: "shadowblade",
    build: "carry",
    flavor: "Cô lưu lạc giữa mạng lưới ngầm thành phố, chuyên xử lý quý tộc thối nát.",
  },
  {
    id: "h_thalas",
    name: "Thalas Lửa Ngàn",
    title: "Pyromancer Tha Hương",
    rarity: "rare",
    range: "ranged",
    role: "mage",
    origins: ["human", "elemental"],
    baseStats: s({ hp: 700, atk: 50, mag: 165, def: 35, res: 70, spd: 100, crit: 12, critDmg: 160 }),
    growth: { hp: 50, mag: 15, res: 3 },
    skills: ["fireball", "iceLance", "meteor"],
        bonusSkills: [
      { skillId: "glacialTrap", unlockCondition: { type: "heroLevel", level: 22 } },
      { skillId: "infernalCore", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "elementalSurge",
    build: "burst",
    flavor: "Cha mẹ mất trong trận hỏa hoạn, anh học cách điều khiển ngọn lửa của định mệnh.",
  },
  {
    id: "h_ravi",
    name: "Ravi Móng Hổ",
    title: "Đấu Sĩ Hổ Tộc",
    rarity: "rare",
    range: "melee",
    role: "warrior",
    origins: ["beastkin"],
    baseStats: s({ hp: 1000, atk: 140, def: 70, res: 40, spd: 110, crit: 12, critDmg: 160, acc: 95, lifesteal: 10 }),
    growth: { hp: 80, atk: 12, def: 5, lifesteal: 0.5 },
    skills: ["bleedSlash", "feralLeap", "whirlwind"],
        bonusSkills: [
      { skillId: "woundDeepen", unlockCondition: { type: "heroLevel", level: 20 } },
      { skillId: "tigerPounce", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "bloodthirst",
    build: "bruiser",
    flavor: "Lãnh chúa mới của bộ lạc Hổ Vàng, vuốt anh sắc như lưỡi dao tử thần.",
  },
  {
    id: "h_ember",
    name: "Ember Núi Khói",
    title: "Pháo Thủ Lưu Vong",
    rarity: "rare",
    range: "ranged",
    role: "marksman",
    origins: ["human", "outlaw"],
    baseStats: s({ hp: 750, atk: 135, def: 40, res: 40, spd: 125, crit: 20, critDmg: 170, acc: 100 }),
    growth: { hp: 55, atk: 11, spd: 2 },
    skills: ["pierceShot", "rapidFire", "trueShot"],
        bonusSkills: [
      { skillId: "scatterBomb", unlockCondition: { type: "heroLevel", level: 20 } },
      { skillId: "deadEyeShot", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "marksmanship",
    build: "attack-speed",
    flavor: "Một xạ thủ bị truy nã, súng trường cô không bao giờ rời tay.",
  },
  {
    id: "h_priestess",
    name: "Aelinor Ánh Bạc",
    title: "Nữ Tu Vầng Trăng",
    rarity: "rare",
    range: "ranged",
    role: "support",
    origins: ["human", "celestial"],
    baseStats: s({ hp: 800, atk: 50, mag: 130, def: 50, res: 90, spd: 95, crit: 5, critDmg: 150 }),
    growth: { hp: 65, mag: 12, res: 5 },
    skills: ["heal", "blessing", "groupHeal"],
        bonusSkills: [
      { skillId: "prayerShield", unlockCondition: { type: "heroLevel", level: 22 } },
      { skillId: "moonlightSurge", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "guardianAura",
    build: "support",
    flavor: "Người được ban phước bởi Nữ Thần Trăng, ánh sáng cô chữa lành mọi vết thương.",
  },

  // ============================================================
  // EPIC (5)
  // ============================================================
  {
    id: "h_kael",
    name: "Kael Thiên Lôi",
    title: "Hoàng Tử Sấm",
    rarity: "epic",
    range: "melee",
    role: "warrior",
    origins: ["human", "elemental"],
    baseStats: s({ hp: 1150, atk: 165, mag: 60, def: 80, res: 60, spd: 115, crit: 18, critDmg: 170 }),
    growth: { hp: 90, atk: 14, def: 6, spd: 2 },
    skills: ["slash", "executioner", "chainLightning"],
        bonusSkills: [
      { skillId: "thunderMantle", unlockCondition: { type: "heroLevel", level: 25 } },
      { skillId: "stormjudgment", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "ironWill",
    build: "bruiser",
    flavor: "Mang trong mình huyết thống thần sấm, mỗi nhát chém đều nổ tung như tia chớp.",
  },
  {
    id: "h_nyx",
    name: "Nyx Vũ Bóng",
    title: "Sát Thủ Hư Vô",
    rarity: "epic",
    range: "melee",
    role: "assassin",
    origins: ["demon", "outlaw"],
    baseStats: s({ hp: 850, atk: 175, def: 45, res: 50, spd: 145, crit: 35, critDmg: 200, acc: 100, lifesteal: 15 }),
    growth: { hp: 60, atk: 15, spd: 2, crit: 1.5 },
    skills: ["shadowStrike", "deathMark", "finalEclipse"],
    bonusSkills: [
      { skillId: "bloodFrenzy", unlockCondition: { type: "twoSkillsMaxLevel" } },
      { skillId: "bladeDance", unlockCondition: { type: "skillCombo", skillIds: ["shadowStrike", "deathMark"] } },
    ],
    passive: "shadowblade",
    build: "carry",
    flavor: "Bóng tối là vũ khí, nỗi sợ là thuốc độc — Nyx là hiện thân của cái chết thầm lặng.",
  },
  {
    id: "h_ozric",
    name: "Ozric Mắt Bão",
    title: "Đại Pháp Sư Băng",
    rarity: "epic",
    range: "ranged",
    role: "mage",
    origins: ["ancient", "elemental"],
    baseStats: s({ hp: 800, atk: 50, mag: 195, def: 45, res: 90, spd: 105, crit: 15, critDmg: 170 }),
    growth: { hp: 60, mag: 18, res: 4 },
    skills: ["iceLance", "chainLightning", "iceAge"],
    bonusSkills: [
      { skillId: "meteor", unlockCondition: { type: "allSkillsLevel", level: 4 } },
      { skillId: "voidRift", unlockCondition: { type: "battlesWon", count: 50 } },
    ],
    passive: "spellweaver",
    build: "burst",
    flavor: "Một học giả 300 tuổi trong tháp băng, ánh nhìn anh có thể đóng băng cả đại dương.",
  },
  {
    id: "h_vex",
    name: "Vex Cánh Sắt",
    title: "Lính Đánh Thuê Tương Lai",
    rarity: "epic",
    range: "ranged",
    role: "marksman",
    origins: ["cyber", "outlaw"],
    baseStats: s({ hp: 880, atk: 170, def: 55, res: 50, spd: 135, crit: 22, critDmg: 180, acc: 100 }),
    growth: { hp: 65, atk: 13, spd: 2 },
    skills: ["pierceShot", "cyberOverdrive", "cyberRailgun"],
        bonusSkills: [
      { skillId: "nanotechStrike", unlockCondition: { type: "heroLevel", level: 25 } },
      { skillId: "overclock", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "cyberCore",
    build: "carry",
    flavor: "Bán mình cho một tập đoàn công nghệ cổ, giờ đây cánh tay máy của Vex bắn chết cả thần linh.",
  },
  {
    id: "h_morgath",
    name: "Morgath Vĩnh Cửu",
    title: "Hộ Vệ Lăng Mộ",
    rarity: "epic",
    range: "melee",
    role: "tank",
    origins: ["undead", "ancient"],
    baseStats: s({ hp: 1500, atk: 95, def: 130, res: 100, spd: 75, crit: 5, critDmg: 150, lifesteal: 20 }),
    growth: { hp: 130, atk: 7, def: 9, res: 5 },
    skills: ["shieldBash", "ironBulwark", "earthquake"],
        bonusSkills: [
      { skillId: "soulChain", unlockCondition: { type: "heroLevel", level: 25 } },
      { skillId: "graveTide", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "bulwark",
    build: "tank",
    flavor: "Một hiệp sĩ chết hàng ngàn năm trước, vẫn đứng gác lăng mộ chủ nhân không mệt mỏi.",
  },

  // ============================================================
  // LEGENDARY (5)
  // ============================================================
  {
    id: "h_seraphine",
    name: "Seraphine Bình Minh",
    title: "Thiên Thần Trừng Phạt",
    rarity: "legendary",
    range: "ranged",
    role: "support",
    origins: ["celestial", "human"],
    baseStats: s({ hp: 1100, atk: 70, mag: 220, def: 70, res: 110, spd: 115, crit: 12, critDmg: 170 }),
    growth: { hp: 90, mag: 22, res: 6 },
    skills: ["heal", "blessing", "resurrection"],
        bonusSkills: [
      { skillId: "holyBarrier", unlockCondition: { type: "heroLevel", level: 28 } },
      { skillId: "divineStrike", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "divineBlessing",
    build: "support",
    flavor: "Thiên thần được phái xuống trần để gìn giữ ánh sáng cuối cùng của nhân loại.",
  },
  {
    id: "h_drakthar",
    name: "Drakthar Long Nhãn",
    title: "Đại Đế Long Tộc",
    rarity: "legendary",
    range: "melee",
    role: "warrior",
    origins: ["dragon", "ancient"],
    baseStats: s({ hp: 1450, atk: 200, mag: 100, def: 100, res: 80, spd: 110, crit: 20, critDmg: 180 }),
    growth: { hp: 110, atk: 17, def: 7, spd: 2 },
    skills: ["bleedSlash", "executioner", "dragonRoar"],
        bonusSkills: [
      { skillId: "dragonScaleMoult", unlockCondition: { type: "heroLevel", level: 30 } },
      { skillId: "ancientDragonRoar", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "dragonHeart",
    build: "bruiser",
    flavor: "Vị vua cuối cùng của Long Tộc, vảy của ngài cứng hơn cả thép thần.",
  },
  {
    id: "h_velka",
    name: "Velka Tử Thi Vũ",
    title: "Nữ Hoàng Bất Tử",
    rarity: "legendary",
    range: "ranged",
    role: "mage",
    origins: ["undead", "demon"],
    baseStats: s({ hp: 1000, atk: 60, mag: 230, def: 65, res: 95, spd: 110, crit: 18, critDmg: 180, lifesteal: 14 }),
    growth: { hp: 75, mag: 23, res: 5, lifesteal: 0.5 },
    skills: ["soulDrain", "fireball", "voidRift"],
        bonusSkills: [
      { skillId: "undeadArmy", unlockCondition: { type: "heroLevel", level: 28 } },
      { skillId: "doomCurse", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "demonPact",
    build: "burst",
    flavor: "Vũ điệu của Velka đánh thức nghìn xác chết, mỗi linh hồn đều rên rỉ tên cô.",
  },
  {
    id: "h_silvanir",
    name: "Silvanir Cung Sao",
    title: "Vua Bắn Trên Đỉnh Núi",
    rarity: "legendary",
    range: "ranged",
    role: "marksman",
    origins: ["ancient", "celestial"],
    baseStats: s({ hp: 1000, atk: 200, def: 65, res: 70, spd: 150, crit: 30, critDmg: 200, acc: 110 }),
    growth: { hp: 75, atk: 16, spd: 3, crit: 1 },
    skills: ["pierceShot", "rapidFire", "trueShot"],
    bonusSkills: [
      { skillId: "cyberRailgun", unlockCondition: { type: "battlesWon", count: 30 } },
      { skillId: "volley", unlockCondition: { type: "skillCombo", skillIds: ["pierceShot", "rapidFire"] } },
    ],
    passive: "marksmanship",
    build: "attack-speed",
    flavor: "Cung của Silvanir được rèn bằng tia sáng đầu tiên của vũ trụ.",
  },
  {
    id: "h_kazumi",
    name: "Kazumi Lưỡi Mưa",
    title: "Sát Thủ Sương Mù",
    rarity: "legendary",
    range: "melee",
    role: "assassin",
    origins: ["beastkin", "outlaw"],
    baseStats: s({ hp: 950, atk: 215, def: 55, res: 55, spd: 160, crit: 40, critDmg: 220, acc: 105, lifesteal: 20 }),
    growth: { hp: 70, atk: 18, spd: 3, crit: 1.5 },
    skills: ["bladeDance", "outlawAmbush", "finalEclipse"],
        bonusSkills: [
      { skillId: "mirrorKill", unlockCondition: { type: "heroLevel", level: 28 } },
      { skillId: "rainDeath", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "shadowblade",
    build: "carry",
    flavor: "Một bóng đen giữa làn mưa, Kazumi chỉ xuất hiện khi nạn nhân đã hết hi vọng.",
  },

  // ============================================================
  // MYTHIC (5)
  // ============================================================
  {
    id: "h_zerathus",
    name: "Zerathus Hủy Thế",
    title: "Vị Thần Quên Lãng",
    rarity: "mythic",
    range: "ranged",
    role: "mage",
    origins: ["ancient", "demon", "elemental"],
    baseStats: s({ hp: 1300, atk: 70, mag: 290, def: 80, res: 130, spd: 125, crit: 25, critDmg: 200 }),
    growth: { hp: 95, mag: 28, res: 6 },
    skills: ["voidRift", "meteor", "starfall"],
    bonusSkills: [
      { skillId: "chainLightning", unlockCondition: { type: "heroLevel", level: 40 } },
      { skillId: "arcaneNova", unlockCondition: { type: "twoSkillsMaxLevel" } },
      { skillId: "divineWrath", unlockCondition: { type: "battlesWon", count: 80 } },
    ],
    passive: "ancientSage",
    build: "burst",
    flavor: "Bị các vị thần khác nhốt trong giếng hư vô, giờ Zerathus trở lại để xé tan thực tại.",
  },
  {
    id: "h_orin",
    name: "Orin Lưỡi Vô Cực",
    title: "Hiệp Sĩ Cuối Cùng",
    rarity: "mythic",
    range: "melee",
    role: "warrior",
    origins: ["human", "celestial", "ancient"],
    baseStats: s({ hp: 1700, atk: 245, def: 130, res: 110, spd: 120, crit: 25, critDmg: 200, acc: 100 }),
    growth: { hp: 130, atk: 20, def: 8, spd: 2 },
    skills: ["bleedSlash", "executioner", "judgment"],
    bonusSkills: [
      { skillId: "whirlwind", unlockCondition: { type: "heroLevel", level: 35 } },
      { skillId: "ironBulwark", unlockCondition: { type: "allSkillsLevel", level: 3 } },
      { skillId: "earthquake", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "ironWill",
    build: "carry",
    flavor: "Người đàn ông duy nhất sống sót sau Đại Thiên Kiếp, gươm anh chia đôi cả số mệnh.",
  },
  {
    id: "h_xara",
    name: "Xara Bóng Quỷ",
    title: "Công Chúa Vực Sâu",
    rarity: "mythic",
    range: "melee",
    role: "assassin",
    origins: ["demon", "undead", "outlaw"],
    baseStats: s({ hp: 1200, atk: 270, def: 70, res: 80, spd: 160, crit: 50, critDmg: 240, acc: 110, lifesteal: 15 }),
    growth: { hp: 85, atk: 22, spd: 3, crit: 2 },
    skills: ["bladeDance", "deathMark", "finalEclipse"],
    bonusSkills: [
      { skillId: "shadowStrike", unlockCondition: { type: "heroLevel", level: 40 } },
      { skillId: "bloodFrenzy", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "demonPact",
    build: "carry",
    flavor: "Sinh ra từ kết hợp giữa địa ngục và lăng mộ — Xara không khoan nhượng cho bất kỳ ai.",
  },
  {
    id: "h_tianlong",
    name: "Tianlong Vạn Cổ",
    title: "Long Đế Thái Sơ",
    rarity: "mythic",
    range: "melee",
    role: "tank",
    origins: ["dragon", "celestial", "ancient"],
    baseStats: s({ hp: 2200, atk: 180, mag: 150, def: 170, res: 140, spd: 95, crit: 15, critDmg: 180, lifesteal: 15 }),
    growth: { hp: 170, atk: 13, def: 11, res: 7 },
    skills: ["dragonBreath", "ironBulwark", "dragonRoar"],
    bonusSkills: [
      { skillId: "earthquake", unlockCondition: { type: "heroLevel", level: 45 } },
      { skillId: "ancientDragonRoar", unlockCondition: { type: "allSkillsLevel", level: 4 } },
    ],
    passive: "dragonHeart",
    build: "tank",
    flavor: "Sinh ra cùng vũ trụ, Long Đế đã ngủ vạn năm — nay tỉnh dậy để hủy diệt một kẻ thù xưa.",
  },
  {
    id: "h_riven",
    name: "Riven Tỷ Hạt",
    title: "Phù Thủy Thiên Hà",
    rarity: "mythic",
    range: "ranged",
    role: "mage",
    origins: ["cyber", "celestial"],
    baseStats: s({ hp: 1250, atk: 70, mag: 310, def: 75, res: 140, spd: 140, crit: 30, critDmg: 210, acc: 105 }),
    growth: { hp: 90, mag: 30, res: 6 },
    skills: ["arcaneBolt", "arcaneNova", "starfall"],
    bonusSkills: [
      { skillId: "voidRift", unlockCondition: { type: "heroLevel", level: 40 } },
      { skillId: "constellationArrow", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "spellweaver",
    build: "burst",
    flavor: "Riven thao túng cả các hằng số vật lý — phép của cô được tính bằng những con số vô tận.",
  },

  // ============================================================
  // CELESTIAL (5)
  // ============================================================
  {
    id: "h_aurion",
    name: "Aurion Bình Minh Vô Tận",
    title: "Đấng Sáng Tạo Ánh Sáng",
    rarity: "celestial",
    range: "ranged",
    role: "support",
    origins: ["celestial", "ancient", "elemental"],
    baseStats: s({ hp: 1700, atk: 80, mag: 360, def: 100, res: 180, spd: 135, crit: 18, critDmg: 200 }),
    growth: { hp: 130, mag: 35, res: 9 },
    skills: ["groupHeal", "blessing", "divineWrath"],
    bonusSkills: [
      { skillId: "resurrection", unlockCondition: { type: "heroLevel", level: 50 } },
      { skillId: "divineStrike", unlockCondition: { type: "allSkillsLevel", level: 4 } },
    ],
    passive: "divineBlessing",
    build: "support",
    flavor: "Người đầu tiên thắp lên mặt trời, ánh sáng của ngài có thể tái tạo cả thực tại đã bị xé.",
  },
  {
    id: "h_morwen",
    name: "Morwen Vực Tối",
    title: "Hoàng Hậu Bóng Đêm Vô Cùng",
    rarity: "celestial",
    range: "melee",
    role: "assassin",
    origins: ["demon", "undead", "celestial"],
    baseStats: s({ hp: 1500, atk: 320, def: 90, res: 110, spd: 195, crit: 60, critDmg: 280, acc: 115, lifesteal: 35 }),
    growth: { hp: 105, atk: 26, spd: 4, crit: 2.5 },
    skills: ["bladeDance", "bloodFrenzy", "soulRend"],
    bonusSkills: [
      { skillId: "shadowStrike", unlockCondition: { type: "heroLevel", level: 45 } },
      { skillId: "doomCurse", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "shadowblade",
    build: "carry",
    flavor: "Khi hoàng hôn cuối cùng buông xuống, Morwen sẽ là người ở lại — và cô lựa chọn ai sống tiếp.",
  },
  {
    id: "h_aetherion",
    name: "Aetherion Vô Hạn",
    title: "Long Thần Của Vũ Trụ",
    rarity: "celestial",
    range: "melee",
    role: "warrior",
    origins: ["dragon", "celestial", "elemental"],
    baseStats: s({ hp: 2000, atk: 300, mag: 200, def: 150, res: 150, spd: 140, crit: 30, critDmg: 220, lifesteal: 20 }),
    growth: { hp: 150, atk: 24, def: 9, spd: 3 },
    skills: ["dragonBreath", "executioner", "dragonRoar"],
    bonusSkills: [
      { skillId: "voidRift", unlockCondition: { type: "heroLevel", level: 50 } },
      { skillId: "ancientDragonRoar", unlockCondition: { type: "allSkillsLevel", level: 5 } },
    ],
    passive: "dragonHeart",
    build: "carry",
    flavor: "Thân hình ngài bao trùm dải Ngân Hà — mỗi nhịp đập trái tim là một vì sao mới ra đời.",
  },
  {
    id: "h_calix",
    name: "Calix Mã Nguồn Vô Tận",
    title: "Tâm Trí Tương Lai",
    rarity: "celestial",
    range: "ranged",
    role: "marksman",
    origins: ["cyber", "ancient", "celestial"],
    baseStats: s({ hp: 1500, atk: 320, def: 90, res: 110, spd: 150, crit: 40, critDmg: 240, acc: 120 }),
    growth: { hp: 100, atk: 25, spd: 4, crit: 2 },
    skills: ["pierceShot", "cyberOverdrive", "voidPulse"],
    bonusSkills: [
      { skillId: "cyberRailgun", unlockCondition: { type: "heroLevel", level: 45 } },
      { skillId: "rainDeath", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "cyberCore",
    build: "carry",
    flavor: "Một AI vượt xa giới hạn, Calix tính toán đường đạn xuyên qua nghìn thực tại.",
  },
  {
    id: "h_yggdra",
    name: "Yggdra Cây Vũ Trụ",
    title: "Mẹ Của Vạn Vật",
    rarity: "celestial",
    range: "ranged",
    role: "tank",
    origins: ["ancient", "elemental", "celestial"],
    baseStats: s({ hp: 2800, atk: 150, mag: 280, def: 200, res: 200, spd: 100, crit: 15, critDmg: 180, lifesteal: 20 }),
    growth: { hp: 220, atk: 11, mag: 25, def: 12, res: 9 },
    skills: ["groupHeal", "earthquake", "voidRift"],
    bonusSkills: [
      { skillId: "blessing", unlockCondition: { type: "heroLevel", level: 45 } },
      { skillId: "pandemicWave", unlockCondition: { type: "allSkillsLevel", level: 4 } },
    ],
    passive: "guardianAura",
    build: "tank",
    flavor: "Nguồn cội của mọi sinh mệnh, mỗi chiếc lá là một hành tinh, mỗi rễ là một dòng thời gian.",
  },

  // ============================================================
  // NEW HEROES — Tộc Mới & Nội Tại Đặc Biệt
  // ============================================================

  // RARE — Phantom Support
  {
    id: "h_vesper",
    name: "Vesper Bóng Lặng",
    title: "Linh Hồn Giữ Đội",
    rarity: "rare",
    range: "ranged",
    role: "support",
    origins: ["phantom", "undead"],
    baseStats: s({ hp: 760, atk: 45, mag: 125, def: 40, res: 80, spd: 110, crit: 8, critDmg: 150, eva: 20 }),
    growth: { hp: 55, mag: 11, res: 4, eva: 0.5 },
    skills: ["heal", "soulDrain", "groupHeal"],
    bonusSkills: [
      { skillId: "phantomStep", unlockCondition: { type: "heroLevel", level: 25 } },
    ],
    passive: "ghostVeil",
    build: "support",
    flavor: "Linh hồn nửa người nửa ma — Vesper bảo vệ đồng đội từ phía bóng tối, không ai thấy cô ấy cho đến khi quá muộn.",
  },

  // RARE — Plague Mage
  {
    id: "h_morbus",
    name: "Morbus Mục Nát",
    title: "Bác Sĩ Dịch Hạch",
    rarity: "rare",
    range: "ranged",
    role: "mage",
    origins: ["plague", "human"],
    baseStats: s({ hp: 680, atk: 45, mag: 155, def: 30, res: 65, spd: 98, crit: 12, critDmg: 160 }),
    growth: { hp: 48, mag: 14, res: 3 },
    skills: ["plagueCloud", "fireball", "plagueNova"],
    bonusSkills: [
      { skillId: "pestilenceField", unlockCondition: { type: "heroLevel", level: 30 } },
      { skillId: "doomCurse", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "infectiousAura",
    build: "burst",
    flavor: "Từng là bác sĩ giỏi nhất vương quốc, Morbus tự nhiễm dịch hạch để hiểu nó — và giờ coi bệnh tật như nghệ thuật.",
  },

  // EPIC — Storm Marksman
  {
    id: "h_zephyr",
    name: "Zephyr Lưỡi Gió",
    title: "Tiễn Thủ Bão Cát",
    rarity: "epic",
    range: "ranged",
    role: "marksman",
    origins: ["storm", "beastkin"],
    baseStats: s({ hp: 840, atk: 160, def: 50, res: 45, spd: 145, crit: 24, critDmg: 185, acc: 100, eva: 12 }),
    growth: { hp: 62, atk: 13, spd: 3, crit: 1 },
    skills: ["rapidFire", "galeShot", "stormBarrage"],
    bonusSkills: [
      { skillId: "cycloneStrike", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "windRider",
    build: "attack-speed",
    flavor: "Sinh ra trong lốc xoáy, Zephyr chạy nhanh hơn gió và bắn nhiều hơn mưa.",
  },

  // EPIC — Phantom Assassin
  {
    id: "h_lynx",
    name: "Lynx Bóng Đêm",
    title: "Sát Thủ Không Hình",
    rarity: "epic",
    range: "melee",
    role: "assassin",
    origins: ["phantom", "outlaw"],
    baseStats: s({ hp: 820, atk: 168, def: 42, res: 48, spd: 150, crit: 38, critDmg: 210, acc: 105, eva: 25, lifesteal: 12 }),
    growth: { hp: 58, atk: 14, spd: 2, crit: 1.5, eva: 0.3 },
    skills: ["shadowStrike", "phantomStep", "deathMark"],
    bonusSkills: [
      { skillId: "finalEclipse", unlockCondition: { type: "allSkillsLevel", level: 4 } },
    ],
    passive: "ghostVeil",
    build: "carry",
    flavor: "Lynx không tồn tại trong danh sách truy nã vì không ai nhìn thấy cô đủ lâu để vẽ chân dung.",
  },

  // LEGENDARY — Plague Tank (unique: tank that spreads disease)
  {
    id: "h_pestis",
    name: "Pestis Hủ Thân",
    title: "Thần Dịch Bất Tử",
    rarity: "legendary",
    range: "melee",
    role: "tank",
    origins: ["plague", "undead", "demon"],
    baseStats: s({ hp: 1600, atk: 100, mag: 80, def: 145, res: 110, spd: 72, crit: 6, critDmg: 155, lifesteal: 18 }),
    growth: { hp: 135, atk: 8, def: 10, res: 6 },
    skills: ["shieldBash", "plaguePulse", "pestilenceField"],
    bonusSkills: [
      { skillId: "plagueNova", unlockCondition: { type: "battlesWon", count: 40 } },
    ],
    passive: "plagueHost",
    build: "tank",
    flavor: "Cơ thể Pestis là ổ dịch di động — mỗi vết thương rỉ ra nọc độc, mỗi bước đi để lại dấu chân bệnh hoạn.",
  },

  // LEGENDARY — Storm Warrior
  {
    id: "h_raijin",
    name: "Raijin Thiên Lôi Phong",
    title: "Thống Soái Bão Sấm",
    rarity: "legendary",
    range: "melee",
    role: "warrior",
    origins: ["storm", "elemental", "ancient"],
    baseStats: s({ hp: 1380, atk: 195, mag: 80, def: 95, res: 75, spd: 130, crit: 22, critDmg: 185, acc: 100 }),
    growth: { hp: 105, atk: 16, def: 7, spd: 2 },
    skills: ["bleedSlash", "galeSlash", "thunderCyclone"],
    bonusSkills: [
      { skillId: "stormBarrage", unlockCondition: { type: "twoSkillsMaxLevel" } },
      { skillId: "chainLightning", unlockCondition: { type: "heroLevel", level: 35 } },
    ],
    passive: "stormChaser",
    build: "bruiser",
    flavor: "Raijin không cần ngựa — anh cưỡi bão. Mỗi bước tiến của đội quân anh đi cùng với tiếng sấm.",
  },

  // MYTHIC — Phantom Mage (mirror-damage caster)
  {
    id: "h_spectra",
    name: "Spectra Hư Ảnh Vạn Hóa",
    title: "Đại Huyễn Pháp Sư",
    rarity: "mythic",
    range: "ranged",
    role: "mage",
    origins: ["phantom", "celestial", "ancient"],
    baseStats: s({ hp: 1180, atk: 65, mag: 285, def: 70, res: 130, spd: 128, crit: 28, critDmg: 205, eva: 20 }),
    growth: { hp: 88, mag: 27, res: 6, eva: 0.5 },
    skills: ["phantomEcho", "arcaneNova", "mirrorRealm"],
    bonusSkills: [
      { skillId: "voidRift", unlockCondition: { type: "allSkillsLevel", level: 4 } },
      { skillId: "starfall", unlockCondition: { type: "battlesWon", count: 70 } },
    ],
    passive: "mirrorSoul",
    build: "burst",
    flavor: "Spectra tạo ra vô số phân thân — kẻ thù không biết đâu là thật. Khi tìm ra, đã quá muộn.",
  },

  // MYTHIC — Storm Marksman (dual-carry)
  {
    id: "h_typhon",
    name: "Typhon Bão Khổng Lồ",
    title: "Pháo Thủ Lốc Xoáy",
    rarity: "mythic",
    range: "ranged",
    role: "marksman",
    origins: ["storm", "cyber", "elemental"],
    baseStats: s({ hp: 1280, atk: 265, def: 80, res: 85, spd: 155, crit: 35, critDmg: 225, acc: 115, eva: 15 }),
    growth: { hp: 92, atk: 21, spd: 3, crit: 1.5 },
    skills: ["stormBarrage", "cyberOverdrive", "tempestBlast"],
    bonusSkills: [
      { skillId: "cyberRailgun", unlockCondition: { type: "twoSkillsMaxLevel" } },
      { skillId: "cycloneStrike", unlockCondition: { type: "battlesWon", count: 60 } },
    ],
    passive: "stormChaser",
    build: "carry",
    flavor: "Typhon ghép súng railgun vào cánh bão. Mỗi viên đạn của anh kéo theo một cơn lốc xoáy nhỏ.",
  },

  // CELESTIAL — Plague Support (anti-heal, epidemic lord)
  {
    id: "h_nemesis_plague",
    name: "Nemesis Đại Dịch",
    title: "Mẹ Của Mọi Bệnh Tật",
    rarity: "celestial",
    range: "ranged",
    role: "support",
    origins: ["plague", "demon", "celestial"],
    baseStats: s({ hp: 1850, atk: 85, mag: 350, def: 110, res: 170, spd: 128, crit: 20, critDmg: 200 }),
    growth: { hp: 140, mag: 34, res: 8 },
    skills: ["plagueNova", "groupHeal", "pandemicWave"],
    bonusSkills: [
      { skillId: "meteor", unlockCondition: { type: "heroLevel", level: 50 } },
      { skillId: "voidRift", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "epidemicGod",
    build: "support",
    flavor: "Các vị thần khác cai trị bầu trời, đại dương, hay đất đai. Nemesis cai trị tế bào — và không ai thoát khỏi tay cô.",
  },

  // CELESTIAL — Storm/Phantom hybrid (ultimate evasion carry)
  {
    id: "h_mirage",
    name: "Mirage Bão Ảo Vô Hình",
    title: "Hoàng Đế Không Ai Thấy",
    rarity: "celestial",
    range: "melee",
    role: "assassin",
    origins: ["phantom", "storm", "outlaw"],
    baseStats: s({ hp: 1620, atk: 340, def: 95, res: 100, spd: 205, crit: 65, critDmg: 295, acc: 120, eva: 55, lifesteal: 28 }),
    growth: { hp: 115, atk: 27, spd: 4, crit: 2.5, eva: 1 },
    passive: "etherealStorm",
    build: "carry",
    flavor: "Không gió, không bóng. Mirage đánh trước khi bạn nhận ra có người ở đó — và biến mất trước khi bạn ngã xuống.",
    skills: ["phantomStep", "bladeDance", "stormEclipse"],
    bonusSkills: [
      { skillId: "finalEclipse", unlockCondition: { type: "twoSkillsMaxLevel" } },
      { skillId: "cycloneStrike", unlockCondition: { type: "skillCombo", skillIds: ["phantomStep", "bladeDance"] } },
    ],
  },
  // ============================================================
  // ADDITIONAL HEROES — Completing faction minimums (5 per faction)
  // ============================================================

  // DRAGON faction — need 2 more (currently 3: drakthar, tianlong, aetherion)
  {
    id: "h_scalebreaker",
    name: "Scalebreaker Hồng Diệm",
    title: "Thợ Săn Long Tộc",
    rarity: "epic",
    range: "melee",
    role: "assassin",
    origins: ["dragon", "outlaw"],
    baseStats: s({ hp: 900, atk: 182, def: 55, res: 50, spd: 148, crit: 36, critDmg: 205, acc: 105, lifesteal: 14 }),
    growth: { hp: 68, atk: 15, spd: 2, crit: 1.5 },
    skills: ["bladeDance", "earthquake", "deathMark"],
    bonusSkills: [
      { skillId: "dragonScaleMoult", unlockCondition: { type: "heroLevel", level: 28 } },
      { skillId: "finalEclipse", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "riskTaker",
    build: "carry",
    flavor: "Kẻ duy nhất từng giết một con rồng một mình — giờ anh mang vảy nó như chiến tích.",
  },
  {
    id: "h_wyrmcaller",
    name: "Wyrmcaller Hỏa Linh",
    title: "Pháp Sư Triệu Hồi Rồng",
    rarity: "legendary",
    range: "ranged",
    role: "mage",
    origins: ["dragon", "elemental", "ancient"],
    baseStats: s({ hp: 1050, atk: 55, mag: 218, def: 70, res: 95, spd: 112, crit: 16, critDmg: 175 }),
    growth: { hp: 80, mag: 21, res: 4 },
    skills: ["fireball", "dragonBreath", "meteor"],
    bonusSkills: [
      { skillId: "ancientDragonRoar", unlockCondition: { type: "heroLevel", level: 32 } },
      { skillId: "arcaneNova", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "dragonHeart",
    build: "burst",
    flavor: "Cô ấy không điều khiển rồng — cô ấy là rồng, chỉ đang mặc lốt người.",
  },

  // PLAGUE faction — need 2 more (currently 3: morbus, pestis, nemesis_plague)
  {
    id: "h_rotweaver",
    name: "Rotweaver Thối Hóa",
    title: "Phù Thủy Mục Nát",
    rarity: "rare",
    range: "ranged",
    role: "mage",
    origins: ["plague", "undead"],
    baseStats: s({ hp: 660, atk: 42, mag: 148, def: 28, res: 62, spd: 97, crit: 11, critDmg: 158 }),
    growth: { hp: 46, mag: 13, res: 3 },
    skills: ["plagueCloud", "soulDrain", "plagueNova"],
    bonusSkills: [
      { skillId: "fireball", unlockCondition: { type: "heroLevel", level: 18 } },
      { skillId: "pestilenceField", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "infectiousAura",
    build: "burst",
    flavor: "Xương ngón tay Rotweaver đã mục từ lâu — nhưng phép thuật từ đó lại mạnh hơn bao giờ.",
  },
  {
    id: "h_carrier",
    name: "Carrier Ký Sinh",
    title: "Vật Chủ Đại Dịch",
    rarity: "epic",
    range: "melee",
    role: "warrior",
    origins: ["plague", "beastkin"],
    baseStats: s({ hp: 1100, atk: 155, def: 78, res: 55, spd: 108, crit: 14, critDmg: 168, lifesteal: 12 }),
    growth: { hp: 84, atk: 13, def: 6, lifesteal: 0.3 },
    skills: ["bleedSlash", "plaguePulse", "pestilenceField"],
    bonusSkills: [
      { skillId: "woundDeepen", unlockCondition: { type: "heroLevel", level: 25 } },
      { skillId: "thunderCyclone", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "plagueHost",
    build: "bruiser",
    flavor: "Người sói nhiễm dịch hạch — cơ thể thú hoang cộng với vi khuẩn cổ đại là tổ hợp chết chóc.",
  },

  // BEASTKIN faction — need 1 more (currently 4: grom, ravi, kazumi, zephyr)
  {
    id: "h_thornmaw",
    name: "Thornmaw Gai Nhọn",
    title: "Chiến Binh Kền Kền",
    rarity: "epic",
    range: "melee",
    role: "tank",
    origins: ["beastkin", "ancient"],
    baseStats: s({ hp: 1350, atk: 105, def: 125, res: 85, spd: 82, crit: 8, critDmg: 155, lifesteal: 16 }),
    growth: { hp: 105, atk: 8, def: 9, res: 4 },
    skills: ["shieldBash", "ironBulwark", "whirlwind"],
    bonusSkills: [
      { skillId: "immovableStance", unlockCondition: { type: "heroLevel", level: 25 } },
      { skillId: "graveTide", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "bulwark",
    build: "tank",
    flavor: "Chim ưng khổng lồ già nhất bộ lạc — lớp lông cứng như giáp sắt, mắt nhìn qua bóng tối.",
  },

  // CYBER faction — need 1 more (currently 4: vex, riven, calix, typhon)
  {
    id: "h_ghostcode",
    name: "Ghostcode Mã Bóng",
    title: "Hacker Hư Vô",
    rarity: "legendary",
    range: "ranged",
    role: "support",
    origins: ["cyber", "phantom"],
    baseStats: s({ hp: 980, atk: 60, mag: 175, def: 60, res: 120, spd: 145, crit: 14, critDmg: 172, eva: 20 }),
    growth: { hp: 75, mag: 17, res: 5, eva: 0.3 },
    skills: ["heal", "nanotechStrike", "overclock"],
    bonusSkills: [
      { skillId: "phantomStep", unlockCondition: { type: "heroLevel", level: 30 } },
      { skillId: "cyberRailgun", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "ghostVeil",
    build: "support",
    flavor: "Một AI đã tự tải mình vào thế giới thực — Ghostcode tồn tại cả ở hai chiều không gian cùng lúc.",
  },

  // PHANTOM faction — need 1 more (currently 4: vesper, lynx, spectra, mirage)
  {
    id: "h_wraithblade",
    name: "Wraithblade Hồn Kiếm",
    title: "Hiệp Sĩ Ma Giới",
    rarity: "legendary",
    range: "melee",
    role: "warrior",
    origins: ["phantom", "undead", "ancient"],
    baseStats: s({ hp: 1250, atk: 192, def: 88, res: 80, spd: 122, crit: 20, critDmg: 185, eva: 18, lifesteal: 15 }),
    growth: { hp: 96, atk: 16, def: 6, spd: 2, eva: 0.2 },
    skills: ["shadowStrike", "ironBulwark", "judgment"],
    bonusSkills: [
      { skillId: "soulChain", unlockCondition: { type: "heroLevel", level: 30 } },
      { skillId: "nightmareStep", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "mirrorSoul",
    build: "bruiser",
    flavor: "Kiếm của Wraithblade được rèn từ xương linh hồn — khi đâm vào ai, nó hút luôn bóng của họ.",
  },

  // STORM faction — need 1 more (currently 4: zephyr, raijin, typhon, mirage)
  {
    id: "h_tempestrix",
    name: "Tempestrix Lốc Tố",
    title: "Phù Thủy Bão Điện",
    rarity: "legendary",
    range: "ranged",
    role: "mage",
    origins: ["storm", "elemental", "celestial"],
    baseStats: s({ hp: 1020, atk: 55, mag: 205, def: 60, res: 88, spd: 128, crit: 19, critDmg: 178, acc: 105 }),
    growth: { hp: 78, mag: 20, res: 4 },
    skills: ["chainLightning", "stormBarrage", "thunderCyclone"],
    bonusSkills: [
      { skillId: "frozenField", unlockCondition: { type: "heroLevel", level: 32 } },
      { skillId: "tempestBlast", unlockCondition: { type: "twoSkillsMaxLevel" } },
    ],
    passive: "stormChaser",
    build: "burst",
    flavor: "Tempestrix gọi sét bằng cách hát — giọng cô khiến mây đen kéo đến và trời gầm thét.",
  },

]

export const HEROES_BY_ID: Record<string, HeroTemplate> = HEROES.reduce(
  (acc, h) => {
    acc[h.id] = h
    return acc
  },
  {} as Record<string, HeroTemplate>,
)

export const HEROES_BY_RARITY: Record<Rarity, HeroTemplate[]> = HEROES.reduce(
  (acc, h) => {
    if (!acc[h.rarity]) acc[h.rarity] = []
    acc[h.rarity].push(h)
    return acc
  },
  {} as Record<Rarity, HeroTemplate[]>,
)
